# koa 框架中错误异常分类

## 错误分类

### 错误 1:路由的 404 错误

重现方法:地址中随便录入一个不存在的路由

### 错误 2:koa-onerror 可捕获错误:中间件错误,HTTP 错误,路由错误,status 错误,未捕获的异常

中间件错误重现方法:在 app.js 中加入如下代码,然后随便访问一个路由触发,

```js
app.use(async (ctx, next) => {
  //语法错误
  test1();
  //抛出错误
  throw new Error("Oops!");
});
```

路由异常触发:
访问 /throwError 触发

### 错误 3:app.on('error') 捕获的错误

在 koa 中，有一类错误是不会被 koa-onerror 捕获但是可以被 app.on('error')捕获的。这类错误通常是由于 Node.js 本身的问题引起的，例如内存泄漏、DNS 解析错误、TLS 握手失败等等。这些错误可能会导致 Node.js 进程崩溃或无法正常工作，因此需要使用 app.on('error')来捕获和处理。比如

- 中间件内的异步错误
  错误处理中间件 koa-onerror 只能捕获同步代码中的错误。如果在异步操作中发生错误，错误处理中间件可能会跳过，而异步操作的回调函数可能会抛出错误。这种情况下，只能使用 app.on('error')捕获错误。

```js
// 以下代码拷贝到app.js的 useErrorHandler()下,然后任意访问个路由即可触发
app.use(async (ctx, next) => {
  // 异步函数模拟
  const fn = () => {
    return new Promise((_resolve, reject) => {
      setTimeout(() => {
        reject("reject");
      }, 1000);
    });
  };
  try {
    // await过程中发生的错误,会被onerror捕获,并返回给前端
    await fn();
  } catch (error) {
    //触发app.on('error'),此时浏览器已经响应完成跳出了koa-onerror的处理范围,但是还在洋葱模型内,所以被app.on('error')捕获
    throw new Error("reject");
  }

  // 下面的代码不使用await,跳出了koa的监控范围,只能被process.on捕获
  fn().catch((e) => {
    throw new Error("reject1");
  });
});
```

-跨域请求错误
如果应用程序接收跨域请求，并且请求的来源不在允许的列表中，错误处理中间件可能无法捕获错误。这是因为 Koa 中的 CORS 中间件会在错误处理中间件之前处理跨域请求，并尝试发送“preflight”请求以确定请求是否允许。如果“preflight”请求失败，错误处理中间件可能无法捕获错误。

```js
// 跨域请求错误示例
app.use(
  cors({
    origin: "https://example.com",
  })
);

app.use(async (ctx, next) => {
  // 这里的错误可能只能被'app.on('error')'捕获
});
```

触发方法待测试:

### 错误 4: process.on 捕获的错误,不在洋葱模型内的所有异常都会在这里捕获,这种错误无法返回给客户端

这类错误包括但不仅限于 app.on('error')错误
在 Node.js 中，一些致命的错误（如内存溢出、未捕获的异常、未处理的 Promise rejection 等）可以被 process.on('uncaughtException')和 process.on('unhandledRejection')事件捕获。这些事件可以用来捕获应用程序中未被处理的异常，以便记录错误信息、发送警报或执行其他操作。

- 路由中的 setttimeout 错误,

  ```js
  // 以下异常跳出了洋葱范围,只能通过 process 来进行捕获
  setTimeout(() => {
    //此时已经跳出了koa的洋葱模型
    throw new error("xxx");
  }, 1000);
  ```

  /throwError 路由代码中已模拟

- reject 错误
  路由代码中异步抛出异常,跳出了洋葱范围,等同于上面的 settimeout 原理

- app.js 入口文件中的代码错误
  在 onerror(app); 下面增加 test1();即可触发,

## 错误处理 hook

封装了一个 useErrorHandler.js hook,使用时一句话即可处理完成

## 测试方法
